import type { Department, UseCase } from "./types";

export const seedDepartments: Department[] = [
  { name: "HR", monthlyBudget: 2000 },
  { name: "Finance", monthlyBudget: 5000 },
  { name: "Operations", monthlyBudget: 3500 },
  { name: "IT", monthlyBudget: 5000 },
];

export const seedUseCases: UseCase[] = [
  {
    id: "uc-contract-clauses",
    name: "Contract clause extraction",
    department: "Finance",
    owner: "Lena Hoffmann",
    status: "Production",
    category: "Gen",
    usagePattern: "user-driven",
    totalUsers: 45,
    timeSavedPerUserPerMonth: 4.5,
    expectedMonthlyCost: 3200,
    peakUsage: "Quarter-end contract renewals",
    fallback: "Manual legal review",
    confidence: "Medium",
  },
  {
    id: "uc-monthly-close",
    name: "Monthly close Excel validation",
    department: "Finance",
    owner: "Jonas Weber",
    status: "Production",
    category: "Automation",
    usagePattern: "system-driven",
    totalUsers: 30,
    timeSavedPerUserPerMonth: 6,
    expectedMonthlyCost: 1400,
    peakUsage: "First 5 business days of the month",
    fallback: "Manual tie-out checklist",
    confidence: "High",
  },
  {
    id: "uc-invoice-coding",
    name: "Invoice coding suggestions",
    department: "Finance",
    owner: "Sofia Ricci",
    status: "POC",
    category: "Hybrid",
    usagePattern: "system-driven",
    totalUsers: 120,
    timeSavedPerUserPerMonth: 1.5,
    expectedMonthlyCost: 900,
    peakUsage: "Month-end AP run",
    fallback: "Rule-based coding engine",
    confidence: "Low",
  },
  {
    id: "uc-hr-chatbot",
    name: "HR policy chatbot",
    department: "HR",
    owner: "Priya Nair",
    status: "Production",
    category: "Gen",
    usagePattern: "user-driven",
    totalUsers: 800,
    timeSavedPerUserPerMonth: 0.5,
    expectedMonthlyCost: 850,
    peakUsage: "Open enrollment & policy updates",
    fallback: "HR shared inbox",
    confidence: "Medium",
  },
  {
    id: "uc-onboarding-docs",
    name: "Onboarding doc generator",
    department: "HR",
    owner: "Marta Kowalska",
    status: "Idea",
    category: "Gen",
    usagePattern: "user-driven",
    totalUsers: 60,
    timeSavedPerUserPerMonth: 2,
    expectedMonthlyCost: 600,
    peakUsage: "Quarterly hiring waves",
    fallback: "Template library",
    confidence: "Low",
  },
  {
    id: "uc-shift-handover",
    name: "Shift handover summaries",
    department: "Operations",
    owner: "Tomás Silva",
    status: "Pilot",
    category: "Gen",
    usagePattern: "system-driven",
    totalUsers: 140,
    timeSavedPerUserPerMonth: 1,
    expectedMonthlyCost: 700,
    peakUsage: "Shift changes at 06:00 / 14:00 / 22:00",
    fallback: "Handwritten shift log",
    confidence: "Low",
  },
  {
    id: "uc-supplier-triage",
    name: "Supplier email triage",
    department: "Operations",
    owner: "Anna Lindqvist",
    status: "POC",
    category: "Agent",
    usagePattern: "system-driven",
    totalUsers: 35,
    timeSavedPerUserPerMonth: 3,
    expectedMonthlyCost: 1100,
    peakUsage: "Peak season (Q4)",
    fallback: "Shared mailbox rules",
    confidence: "Medium",
  },
  {
    id: "uc-incident-summaries",
    name: "Incident summary drafting",
    department: "IT",
    owner: "Marc Dubois",
    status: "Pilot",
    category: "Gen",
    usagePattern: "user-driven",
    totalUsers: 90,
    timeSavedPerUserPerMonth: 2.5,
    expectedMonthlyCost: 1300,
    peakUsage: "Major incident bridges",
    fallback: "On-call scribe",
    confidence: "Medium",
  },
  {
    id: "uc-helpdesk-bot",
    name: "Helpdesk ticket deflection bot",
    department: "IT",
    owner: "Elena Petrova",
    status: "Production",
    category: "Agent",
    usagePattern: "user-driven",
    totalUsers: 650,
    timeSavedPerUserPerMonth: 0.75,
    expectedMonthlyCost: 2400,
    peakUsage: "Monday mornings & patch days",
    fallback: "L1 helpdesk queue",
    confidence: "High",
  },
  {
    id: "uc-code-review",
    name: "Code review assistant",
    department: "IT",
    owner: "David Chen",
    status: "Stopped",
    category: "Hybrid",
    usagePattern: "user-driven",
    totalUsers: 25,
    timeSavedPerUserPerMonth: 1,
    expectedMonthlyCost: 450,
    peakUsage: "Release freeze weeks",
    fallback: "Peer review",
    confidence: "Low",
  },
];
