import type { Department, Initiative } from "./types";

export const seedDepartments: Department[] = [
  { name: "HR", monthlyBudget: 2000 },
  { name: "Finance", monthlyBudget: 5000 },
  { name: "Operations", monthlyBudget: 3500 },
  { name: "IT", monthlyBudget: 5000 },
];

/**
 * Generic-plausible enterprise initiatives — never named-company flavored.
 * Perceived value and build effort are seeded judgments; the two High-
 * confidence entries carry actuals so the reconcile view has something real
 * to show. Verdict spread: two quick wins, three strategic bets, three
 * fillers, one trap (Supplier email triage — the expensive thing nobody
 * feels), one stopped.
 */
export const seedInitiatives: Initiative[] = [
  {
    id: "init-contract-clauses",
    name: "Contract clause extraction",
    department: "Finance",
    owner: "Lena Hoffmann",
    status: "Production",
    category: "Gen",
    usagePattern: "user-driven",
    totalUsers: 45,
    timeSavedPerUserPerMonth: 4.5,
    expectedMonthlyCost: 3200,
    peakUsage: "Quarter-end contract renewals",
    fallback: "Manual legal review",
    confidence: "Medium",
    perceivedValue: 4,
    buildEffort: "L",
  },
  {
    id: "init-monthly-close",
    name: "Monthly close Excel validation",
    department: "Finance",
    owner: "Jonas Weber",
    status: "Production",
    category: "Automation",
    usagePattern: "system-driven",
    totalUsers: 30,
    timeSavedPerUserPerMonth: 6,
    expectedMonthlyCost: 1400,
    peakUsage: "First 5 business days of the month",
    fallback: "Manual tie-out checklist",
    confidence: "High",
    perceivedValue: 4,
    buildEffort: "M",
    actuals: {
      monthlyCost: 1310,
      hoursSavedPerMonth: 205,
      quality: "measured",
      recordedAt: "2026-06-05T00:00:00.000Z",
    },
  },
  {
    id: "init-invoice-coding",
    name: "Invoice coding suggestions",
    department: "Finance",
    owner: "Sofia Ricci",
    status: "POC",
    category: "Hybrid",
    usagePattern: "system-driven",
    totalUsers: 120,
    timeSavedPerUserPerMonth: 1.5,
    expectedMonthlyCost: 900,
    peakUsage: "Month-end AP run",
    fallback: "Rule-based coding engine",
    confidence: "Low",
    perceivedValue: 2,
    buildEffort: "S",
  },
  {
    id: "init-hr-chatbot",
    name: "HR policy chatbot",
    department: "HR",
    owner: "Priya Nair",
    status: "Production",
    category: "Gen",
    usagePattern: "user-driven",
    totalUsers: 800,
    timeSavedPerUserPerMonth: 0.5,
    expectedMonthlyCost: 850,
    peakUsage: "Open enrollment & policy updates",
    fallback: "HR shared inbox",
    confidence: "Medium",
    perceivedValue: 4,
    buildEffort: "S",
  },
  {
    id: "init-onboarding-docs",
    name: "Onboarding doc generator",
    department: "HR",
    owner: "Marta Kowalska",
    status: "Idea",
    category: "Gen",
    usagePattern: "user-driven",
    totalUsers: 60,
    timeSavedPerUserPerMonth: 2,
    expectedMonthlyCost: 600,
    peakUsage: "Quarterly hiring waves",
    fallback: "Template library",
    confidence: "Low",
    perceivedValue: 3,
    buildEffort: "M",
  },
  {
    id: "init-shift-handover",
    name: "Shift handover summaries",
    department: "Operations",
    owner: "Tomás Silva",
    status: "Pilot",
    category: "Gen",
    usagePattern: "system-driven",
    totalUsers: 140,
    timeSavedPerUserPerMonth: 1,
    expectedMonthlyCost: 700,
    peakUsage: "Shift changes at 06:00 / 14:00 / 22:00",
    fallback: "Handwritten shift log",
    confidence: "Low",
    perceivedValue: 3,
    buildEffort: "S",
  },
  {
    id: "init-supplier-triage",
    name: "Supplier email triage",
    department: "Operations",
    owner: "Anna Lindqvist",
    status: "POC",
    category: "Agent",
    usagePattern: "system-driven",
    totalUsers: 35,
    timeSavedPerUserPerMonth: 3,
    expectedMonthlyCost: 1100,
    peakUsage: "Peak season (Q4)",
    fallback: "Shared mailbox rules",
    confidence: "Medium",
    perceivedValue: 2,
    buildEffort: "L",
  },
  {
    id: "init-incident-summaries",
    name: "Incident summary drafting",
    department: "IT",
    owner: "Marc Dubois",
    status: "Pilot",
    category: "Gen",
    usagePattern: "user-driven",
    totalUsers: 90,
    timeSavedPerUserPerMonth: 2.5,
    expectedMonthlyCost: 1300,
    peakUsage: "Major incident bridges",
    fallback: "On-call scribe",
    confidence: "Medium",
    perceivedValue: 4,
    buildEffort: "S",
  },
  {
    id: "init-helpdesk-bot",
    name: "Helpdesk ticket deflection bot",
    department: "IT",
    owner: "Elena Petrova",
    status: "Production",
    category: "Agent",
    usagePattern: "user-driven",
    totalUsers: 650,
    timeSavedPerUserPerMonth: 0.75,
    expectedMonthlyCost: 2400,
    peakUsage: "Monday mornings & patch days",
    fallback: "L1 helpdesk queue",
    confidence: "High",
    perceivedValue: 4,
    buildEffort: "L",
    actuals: {
      monthlyCost: 2120,
      hoursSavedPerMonth: 430,
      quality: "measured",
      recordedAt: "2026-06-12T00:00:00.000Z",
    },
  },
  {
    id: "init-code-review",
    name: "Code review assistant",
    department: "IT",
    owner: "David Chen",
    status: "Stopped",
    category: "Hybrid",
    usagePattern: "user-driven",
    totalUsers: 25,
    timeSavedPerUserPerMonth: 1,
    expectedMonthlyCost: 450,
    peakUsage: "Release freeze weeks",
    fallback: "Peer review",
    confidence: "Low",
    perceivedValue: 2,
    buildEffort: "M",
  },
];
